# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Chofy App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chofy App
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'IGListKit', '~> 4.0.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'lottie-ios'
  pod 'Alamofire', '~> 5.2'
  pod 'SVProgressHUD'
  
  # Local pods
  pod 'MainApp', :path => '../libraries/MainApp'
  pod 'ChofyExtensions', :path => '../libraries/ChofyExtensions'
  pod 'ChofyStyleGuide', :path => '../libraries/ChofyStyleGuide'

end
